### ISSUE TITLE
decrease the amount of possibilitys

### ISSUE THREAD

**Issue by cyb3rkun** [delight-im/AndroidPatternLock#1]
hay 
I think that it could be useful to add the option to choose the maximum amount of numbers or for a user to choose a specific number:
for example if you only want all possible 4 digit combinations
or if you want all possible combinations containing a specific number like 8 or 5,

or you could make that the user can do both 

in this way if someone uses this list for a brute force because they forgot their pattern these options could help narrow down the possibilities and make the process faster

**Comment by ocram** [comment]
Thanks, these would indeed be excellent additions!

The README already had the *number of combinations* for some of these, under “Number of possible combinations” (both as “by maximum number of connected dots” and “per single number of dots”).

But if you want the actual *list of the combinations* (instead of just the count), this has been added to the README now as well:

You can download `OUTPUT.txt` from this repository here and then run `grep` (Linux), `grep` or GNU `grep` (macOS), or `grep` in WSL (Windows 10+) on it:

> the option to choose the maximum amount of numbers

https://github.com/delight-im/AndroidPatternLock#for-a-maximum-number-of-connected-dots

> to choose a specific number: for example if you only want all possible 4 digit combinations

https://github.com/delight-im/AndroidPatternLock#for-an-exact-number-of-connected-dots

> if you want all possible combinations containing a specific number like 8 or 5

https://github.com/delight-im/AndroidPatternLock#for-a-specific-dot-being-connected

https://github.com/delight-im/AndroidPatternLock#for-multiple-specific-dots-being-connected

**Comment by ocram** [comment]
Pre-generated lists are now also included in the `combinations` folder, and linked to from the README

**Comment by cyb3rkun** [comment]
Thank you these will work perfectly also how do I download and use the
source code?

Im not a skilled programmer or coder but I want to see if i could add a
piece of code to cross reference all of these so that I could narrow down
the possible combinations even more.

You see I forgot my pattern and I'm now looking to see if I can find my
pattern somehow

However looking through more than 300k combinations would be very
inneficient and I also have to wait 30 seconds afer every failed attempt

**Comment by ocram** [comment]
> how do I download and use the source code?

You can download the complete list of all possible combinations, or the filtered lists, by clicking on the links in the README. Alternatively, just click on the `combinations` directory in the file list. When you have clicked on a specific file/list, you then need to click “View raw” and start the download. These lists can then be filtered even more, if you need.

As for the source code, you usually don’t need to run or modify it, unless you want to change the logic of how the lists themselves are generated.

> I want to see if i could add a piece of code to cross reference all of these

The existing lists, and perhaps further filtering (e.g. with `grep`, as shown), should really be all you need.

> You see I forgot my pattern and I'm now looking to see if I can find my pattern somehow

That attempt is unlikely to be successful, unfortunately, unless you remember several details, e.g. the (exact) number of dots connected and possibly several of the positions.

> However looking through more than 300k combinations would be very inneficient and I also have to wait 30 seconds afer every failed attempt

Yes, that’s why the pattern lock is relatively safe – which is usually a good thing.

**Comment by cyb3rkun** [comment]
That attempt is unlikely to be successful, unfortunately, unless you
remember several details, e.g. the (exact) number of dots connected and
possibly several of the positions.

The reason I want to cross reference them and/cross compare is because I
remember a few of the dots that were connected and the last dot in the
pattern otherwise i would not even try

**Comment by ocram** [comment]
You can start with the smallest available list that still includes your pattern. Then run `grep` to filter with as many details as you can, perhaps even with criteria for every single position:

```bash
$ grep -E '^[0-9][2-7][1,6,9][2-9]$' 'combinations/all.txt'
```

**Comment by cyb3rkun** [comment]
Thank you
But how do I use grep?
Do I tipe it in somewhere on github?
Or do I download the files and run it through CMD or powershell?

I've only ever written code in c so I don't know much about how to do these
things?

**Comment by ocram** [comment]
> Do I tipe it in somewhere on github?

No, must be done locally on your computer.

> Or do I download the files and run it through CMD or powershell?

Yes, almost.

> But how do I use grep?

`grep` is available in Linux’s and macOS’s equivalent of CMD/PowerShell. On Windows, it’s only available if you install WSL. PowerShell might have something similar, like `Select-String -Pattern`, but I’m not familiar with this. Or you might be able to use Notepad++, by opening the list, and using find/replace by searching for `(PATTERN)|^.+$`, e.g. `(^.{,7}$)|^.+$`, and replacing with `\1`.

**Comment by cyb3rkun** [comment]
Thanks for your help I really appreciate it
